# Generated by Django 3.0.8 on 2020-08-04 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('ingrediente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ingrediente', models.CharField(max_length=200)),
                ('costo_ingrediente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(verbose_name='Fecha pedido')),
                ('nombre_cliente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('tamano_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tamano', models.CharField(max_length=200)),
                ('costo_tamano', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.Ingrediente')),
                ('pizza_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.Pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='tamano_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.Tamano'),
        ),
    ]
