# Generated by Django 3.0.8 on 2020-08-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamano_ingrediente',
            name='ingrediente_id',
        ),
        migrations.RemoveField(
            model_name='tamano_ingrediente',
            name='tamano_id',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='costo_ingrediente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingrediente_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.Ingrediente'),
        ),
        migrations.DeleteModel(
            name='Pizza_Ingrediente',
        ),
        migrations.DeleteModel(
            name='Tamano_Ingrediente',
        ),
    ]
