# Generated by Django 3.0.8 on 2020-08-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200803_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingrediente_id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(verbose_name='Fecha pedido'),
        ),
        migrations.CreateModel(
            name='Pizza_Ingrediente',
            fields=[
                ('pizza_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingrediente_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.Ingrediente')),
            ],
        ),
    ]
